### ISSUE TITLE
Navigate from any IgrGridToolbar sample to another causing the error

### ISSUE THREAD

**Issue by igDivya** [IgniteUI/igniteui-react#65]
## Steps to reproduce  

1. Run any IgrGridToolbar sample like this: https://staging.infragistics.com/react-demos/samples/grids/grid/toolbar-style
2.  navigate to any other sample.

## Result  
error in the console:
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ms (https://www.infragistics.com/react-demos/static/js/main.0412b44a.js:2:99557)
    at ds (https://www.infragistics.com/react-demos/static/js/main.0412b44a.js:2:99260)
    at ms (https://www.infragistics.com/react-demos/static/js/main.0412b44a.js:2:100215)
    at ds (https://www.infragistics.com/react-demos/static/js/main.0412b44a.js:2:99260)
    at ms (https://www.infragistics.com/react-demos/static/js/main.0412b44a.js:2:100215)
    at ds (https://www.infragistics.com/react-demos/static/js/main.0412b44a.js:2:99260)
    at ms (https://www.infragistics.com/react-demos/static/js/main.0412b44a.js:2:99794)
    at ds (https://www.infragistics.com/react-demos/static/js/main.0412b44a.js:2:99260)
    at ms (https://www.infragistics.com/react-demos/static/js/main.0412b44a.js:2:99458)
    at ds (https://www.infragistics.com/react-demos/static/js/main.0412b44a.js:2:99260)

## Expected result  
No error

## Attachments  
![image](https://github.com/IgniteUI/igniteui-react/assets/22081100/97ff4669-1360-45ec-aa1a-b201997fc86a)

**Comment by ivanovla** [comment]
I have the same problem. @Lipata may be you have some workaround which we don't know?

**Comment by Lipata** [comment]
@dkamburov should I move it to the samples repo: https://github.com/IgniteUI/igniteui-xplat-docs, or it seems more like e component issue?

**Comment by dkamburov** [comment]
I'd put my bets in the samples. You can move it to samples, we'll check if it's a product one.
