### ISSUE TITLE
IgrToolbar throws console errors - broken CustomTool sample

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-react#89]
Navigate to sample
https://www.infragistics.com/react-demos/samples/charts/toolbar/custom-tool

Source
https://github.com/IgniteUI/igniteui-react-examples/tree/vnext/samples/charts/toolbar/custom-tool

Error 1:

Uncaught Error: each child must have a unique key or name property
    at ContentChildrenManager.js:21:1
    at react.development.js:1195:1
    at react.development.js:1158:1
    at mapIntoArray (react.development.js:1049:1)
    at mapChildren (react.development.js:1157:1)
    at Object.forEachChildren [as forEach] (react.development.js:1194:1)
    at ContentChildrenManager.getChildren (ContentChildrenManager.js:18:1)
    at IgrToolbar.render (igr-toolbar.js:141:1)
    at finishClassComponent (react-dom.development.js:19781:1)
    at updateClassComponent (react-dom.development.js:19727:1)

Error 2:
react-dom.development.js:18704 The above error occurred in the <IgrToolbar> component:

    at IgrToolbar (http://localhost:4200/static/js/bundle.js:242060:24)
    at div
    at div
    at div
    at div
    at Sample (http://localhost:4200/static/js/bundle.js:187:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

Error 3:
Uncaught Error: each child must have a unique key or name property
    at ContentChildrenManager.js:21:1
    at react.development.js:1195:1
    at react.development.js:1158:1
    at mapIntoArray (react.development.js:1049:1)
    at mapChildren (react.development.js:1157:1)
    at Object.forEachChildren [as forEach] (react.development.js:1194:1)
    at ContentChildrenManager.getChildren (ContentChildrenManager.js:18:1)
    at IgrToolbar.render (igr-toolbar.js:141:1)
    at finishClassComponent (react-dom.development.js:19781:1)
    at updateClassComponent (react-dom.development.js:19727:1)

**Comment by mddifilippo89** [comment]
https://github.com/IgniteUI/igniteui-xplat-examples/pull/756
